id: 88ffdebf112c4ecfa3bf7b23a21b58b5
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_731-Tara_Who_Protects_from_Eight_Dangers-v2
  language: bo
  author: ''
  volume: {}
